services:
  - type: web
    name: bioshield-ecg
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app2.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
